// javascript/react/prac/my-first-react-project/src/components/router/router-app/router-app.jsx
import React, {Component} from 'react'
import {Switch, Route, Redirect} from 'react-router-dom'
import MyNavLink from '../router-mynav/router-mynav'
import AboutRoute from '../../../views/about/aboutRoute'
import HomeRoute from '../../../views/home/homeRoute'
export default class App extends Component{
    render(){
        return (
            <div className="container">
                <header className="row">
                    <div className="col-xs-offset-2 col-xs-8">
                        <h1 className="page-header">React Router Demo</h1>
                    </div>
                </header>
                <section className="row">
                    <div className="col-xs-offset-2 col-xs-2">
                        <div className="list-group">  
                            <MyNavLink className="list-group-item" to="/about">About</MyNavLink>
                            <MyNavLink className="list-group-item" to="/Home">Home</MyNavLink>
                        </div>
                    </div>
                    <div className="col-xs-6">
                        <Switch>
                            <Route path="/about" component={AboutRoute}>
                            </Route>
                            <Route path="/Home" component={HomeRoute}>
                            </Route>
                            <Redirect to="/about"></Redirect>
                        </Switch>
                    </div>
                </section>
            </div>
        )
    }
}

// javascript/vue/prac/my-vue-demo/src/RouterApp.vue
<template>
    <div class="container">
        <div class="page-header row">
            <h1 class="col-xs-offset-2">Router-basic</h1>
        </div>
        <div class="row">
            <div class="col-xs-offset-2 col-xs-2">
                <ul class="list-group">
                    <li class="list-group-item">
                        <router-link to="/home">home</router-link>
                    </li>
                    <li class="list-group-item">
                        <router-link to="/about">about</router-link>    
                    </li>    
                </ul>   
            </div>
            <div class="col-xs-8">
                <router-view></router-view>
            </div>  
        </div>
    </div>
</template>

<script>
    export default {
        
    }
</script>

<style>
.router-link-active{
    text-decoration: none!important;
    color: red!important;
}
a:hover{
    text-decoration: none;
}
</style>
